# -*- coding: utf-8 -*-
"""task1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EUSmkLQGDgbmvPAVnzj8Oc4sSxNdpDMW
"""

import requests
import time
import os
import json
from datetime import datetime

TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

headers = {"User-Agent": "TrendPulse/1.0"}

categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

all_stories = []
category_counts = {category: 0 for category in categories}
collected_ids = set()

try:
    response = requests.get(TOP_STORIES_URL, headers=headers, timeout=10)
    response.raise_for_status()
    top_story_ids = response.json()[:500]
    print(f"Successfully fetched {len(top_story_ids)} top story IDs.")

except requests.exceptions.RequestException as error:
    print(f"Failed to fetch top story IDs: {error}")
    top_story_ids = []

for category, keywords in categories.items():
    print(f"\nCollecting {category} stories...")

    for story_id in top_story_ids:
        if category_counts[category] >= 25:
            break

        try:
            story_url = ITEM_URL.format(story_id)

            response = requests.get(
                story_url,
                headers=headers,
                timeout=10
            )

            response.raise_for_status()
            story_data = response.json()

        except requests.exceptions.RequestException as error:
            print(f"Failed to fetch story {story_id}: {error}")
            continue

        if not story_data or story_data.get("type") != "story":
            continue

        title = story_data.get("title")

        if not title:
            continue

        title_lower = title.lower()

        if any(keyword in title_lower for keyword in keywords):
            post_id = story_data.get("id")

            if post_id in collected_ids:
                continue

            story = {
                "post_id": post_id,
                "title": title,
                "category": category,
                "score": story_data.get("score", 0),
                "num_comments": story_data.get("descendants", 0),
                "author": story_data.get("by", "unknown"),
                "collected_at": datetime.now().isoformat()
            }

            all_stories.append(story)
            collected_ids.add(post_id)
            category_counts[category] += 1

            print(
                f"Collected {category_counts[category]}/25 "
                f"{category}: {title}"
            )

    time.sleep(2)

os.makedirs("data", exist_ok=True)

date_today = datetime.now().strftime("%Y%m%d")
file_path = f"data/trends_{date_today}.json"

with open(file_path, "w", encoding="utf-8") as file:
    json.dump(all_stories, file, indent=4, ensure_ascii=False)

print(f"\nCollected {len(all_stories)} stories. Saved to {file_path}")